"""Caching helpers for project-owned code (`config/`, `core/`) — see BASE-DESIGN.md §3.
Not for installed app packages; see `tools/crypto.py`'s docstring for why.

`CACHES["default"]` is `django.core.cache.backends.redis.RedisCache` (Django's own
built-in backend, not `django-redis`), which has no `delete_pattern`/wildcard delete.
Bulk invalidation is therefore done by namespace *versioning*: every key generated by
`build_cache_key` embeds the namespace's current version, and `invalidate_namespace`
bumps that version so every previously-built key simply stops being looked up — no scan,
no wildcard delete, and it works identically against any cache backend.

Keys are namespace-prefixed per APP-DESIGN.md §1.3: one Redis instance is shared by
every installed app, so an unprefixed key from two apps (or an app and the host) can
collide silently.
"""

import hashlib
from collections.abc import Callable
from typing import cast

from django.core.cache import cache

__all__ = ["build_cache_key", "cached_call", "invalidate_namespace", "namespace_version"]

# Keeps generated keys short and free of characters the cache backend (or a log line)
# might treat specially, once a part gets long or contains something other than
# alphanumerics/dashes/underscores/colons/periods.
_MAX_RAW_PART_LEN = 40
_SAFE_PART = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_:.")


def _version_key(namespace: str) -> str:
    return f"{namespace}:version"


def namespace_version(namespace: str) -> int:
    """Returns the current version for `namespace`, creating it at 1 on first use."""
    version = cache.get(_version_key(namespace))
    if version is None:
        version = 1
        cache.set(_version_key(namespace), version, timeout=None)
    return int(version)


def invalidate_namespace(namespace: str) -> int:
    """Bumps `namespace`'s version, invalidating every key previously built against it.

    Returns the new version. Uses `cache.incr`, which requires the version key to
    already exist — call `namespace_version` first if that's not guaranteed, or rely on
    the fact that `build_cache_key`/`cached_call` always create it on first use.
    """
    namespace_version(namespace)  # ensure it exists before incrementing
    return cache.incr(_version_key(namespace))


def _normalize_part(part: object) -> str:
    raw = str(part)
    if len(raw) > _MAX_RAW_PART_LEN or not set(raw) <= _SAFE_PART:
        return hashlib.sha256(raw.encode()).hexdigest()[:16]
    return raw


def build_cache_key(namespace: str, *parts: object) -> str:
    """Builds a stable, namespace-versioned cache key.

    `namespace:version:part1:part2:...` — long or unsafe parts are hashed rather than
    embedded raw, so an arbitrary string (a user-supplied query, say) can't blow up key
    length or smuggle a delimiter into the key.
    """
    version = namespace_version(namespace)
    segments = [namespace, str(version), *(_normalize_part(p) for p in parts)]
    return ":".join(segments)


def cached_call[T](key: str, timeout: int | None, producer: Callable[[], T]) -> T:
    """Get-or-set: returns the cached value at `key`, computing and storing it via
    `producer()` on a miss. `producer` is called at most once per miss.

    A `producer` that returns `None` is never actually cached — Django's cache API can't
    distinguish "miss" from "cached None" through `.get()`'s default. Fine for the
    typical use (caching a queryset result, a serialized dict), but don't reach for this
    to cache a value that's legitimately `None`.
    """
    value = cache.get(key)
    if value is None:
        value = producer()
        cache.set(key, value, timeout=timeout)
    return cast("T", value)
